FROM openjdk:15
ADD ./target/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar /usr/src/spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar", "spring-boot-jpa-postgresql-0.0.1-SNAPSHOT.jar"]